apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchify-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchify-backend
  template:
    metadata:
      labels:
        app: matchify-backend
    spec:
      containers:
        - name: matchify-backend
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: matchify-backend-secret
                  key: JWT_SECRET
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: matchify-db-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: matchify-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matchify-db-secret
                  key: DB_PASSWORD
